// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Models;

public partial class Company
{
    [Key]
    [Column("CompanyID")]
    public int CompanyId { get; set; }

    [Required]
    [Column("Company", TypeName = "text")]
    public string Company1 { get; set; }

    [Column(TypeName = "text")]
    public string Website { get; set; }

    [Column(TypeName = "text")]
    public string Linkedin { get; set; }

    [Column(TypeName = "text")]
    public string ExtraInfo { get; set; }

    [InverseProperty("CompanyNavigation")]
    public virtual ICollection<Job> Jobs { get; set; } = new List<Job>();
}