// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DAL.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DAL.Models
{
    public partial interface IToDoContextProcedures
    {
        Task<List<GetSubtopicsResult>> GetSubtopicsAsync(int? Topic_ID, OutputParameter<int> returnValue = null, 
            CancellationToken cancellationToken = default);
    }
}
