// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Models;

public partial class Job
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    public bool Recruiter { get; set; }

    public bool Linkedin { get; set; }

    public bool Referral { get; set; }

    public bool DirectToSite { get; set; }

    public bool CompanyWebsite { get; set; }

    [Required]
    [Column(TypeName = "text")]
    public string Company { get; set; }

    [Column("Job_title", TypeName = "text")]
    public string JobTitle { get; set; }

    [Column("Date_posted")]
    public DateOnly? DatePosted { get; set; }

    [Column("Date_found")]
    public DateOnly DateFound { get; set; }

    [Column("Date_deadline")]
    public DateOnly? DateDeadline { get; set; }

    [Column("Req_test")]
    public bool? ReqTest { get; set; }

    [Column("Req_cover_letter")]
    public bool? ReqCoverLetter { get; set; }

    [Column("Date_submitted")]
    public DateOnly? DateSubmitted { get; set; }

    [Column("Last_status", TypeName = "text")]
    public string LastStatus { get; set; }

    [Column("Status_date")]
    public DateOnly? StatusDate { get; set; }

    [Column(TypeName = "text")]
    public string Info { get; set; }
}