// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DAL.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DAL.Models
{
    public partial class ToDoContext
    {
        private IToDoContextProcedures _procedures;

        public virtual IToDoContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new ToDoContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IToDoContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class ToDoContextProcedures : IToDoContextProcedures
    {
        private readonly ToDoContext _context;

        public ToDoContextProcedures(ToDoContext context)
        {
            _context = context;
        }

        public virtual async Task<List<GetSubtopicsResult>> GetSubtopicsAsync(int? Topic_ID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Topic_ID",
                    Value = Topic_ID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<GetSubtopicsResult>("EXEC @returnValue = [dbo].[GET_SUBTOPICS] @Topic_ID = @Topic_ID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
