// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DAL.Models.Configurations;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
#nullable disable

namespace DAL.Models;

public partial class ToDoContext : DbContext
{
    public ToDoContext(DbContextOptions<ToDoContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Job> Jobs { get; set; }

    public virtual DbSet<Subtopic> Subtopics { get; set; }

    public virtual DbSet<Topic> Topics { get; set; }

    public virtual DbSet<UnfinishedJob> UnfinishedJobs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.SubtopicConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TopicConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.UnfinishedJobConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
