// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Models;

public partial class Topic
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [StringLength(10)]
    public string Description { get; set; }

    public int? Priority { get; set; }

    [Column("Date_Logged")]
    public DateOnly? DateLogged { get; set; }

    [Column("Long_Descriptions", TypeName = "text")]
    public string LongDescriptions { get; set; }

    [InverseProperty("Topic")]
    public virtual ICollection<Subtopic> Subtopics { get; set; } = new List<Subtopic>();
}