// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Models;

[Keyless]
public partial class UnfinishedJob
{
    [StringLength(10)]
    public string Description { get; set; }

    [Column("Estimated_hours")]
    public int? EstimatedHours { get; set; }

    public bool? Pluralsight { get; set; }

    [Column("Long_description", TypeName = "text")]
    public string LongDescription { get; set; }

    public int? Priority { get; set; }
}