// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DAL.Models.Configurations
{
    public partial class JobConfiguration : IEntityTypeConfiguration<Job>
    {
        public void Configure(EntityTypeBuilder<Job> entity)
        {
            entity.HasOne(d => d.CompanyNavigation).WithMany(p => p.Jobs).HasConstraintName("CompanyID_FK");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Job> entity);
    }
}
