// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DAL.Models.Configurations
{
    public partial class SubtopicConfiguration : IEntityTypeConfiguration<Subtopic>
    {
        public void Configure(EntityTypeBuilder<Subtopic> entity)
        {
            entity.Property(e => e.Description).IsFixedLength();

            entity.HasOne(d => d.Topic).WithMany(p => p.Subtopics).HasConstraintName("FK_Subtopics_Topics");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Subtopic> entity);
    }
}
