// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DAL.Models.Configurations
{
    public partial class UnfinishedJobConfiguration : IEntityTypeConfiguration<UnfinishedJob>
    {
        public void Configure(EntityTypeBuilder<UnfinishedJob> entity)
        {
            entity.ToView("Unfinished_jobs");

            entity.Property(e => e.Description).IsFixedLength();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UnfinishedJob> entity);
    }
}
